### ISSUE TITLE
Unable to create Hmac for Sha384 and Sha512

### ISSUE THREAD

**Issue by GildedHonour** [DaGenix/rust-crypto#240]
Since all Sha256, Sha384, Sha512 implement the trait Digest and Hmac::new accepts Digest, why do I have an error in this code?

```
extern crate crypto;
use crypto::sha2::{Sha256, Sha384, Sha512};
use crypto::hmac::Hmac;
use crypto::digest::Digest;
use crypto::mac::Mac;


enum MyType {
  Type1,
  Type2,
  Type3
}

//......

let mut hmac = Hmac::new(match myType {
   MyType::Type1 => Sha256::new(),
   MyType::Type2 => Sha384::new(),
   MyType::Type3 => Sha512::new()
  }, my_secret.to_string().as_bytes()
);

```
The error is:
```
error: match arms have incompatible types:
 expected `crypto::sha2::Sha256`,
    found `crypto::sha2::Sha384`
(expected struct `crypto::sha2::Sha256`,
    found struct `crypto::sha2::Sha384`) [E0308]
   let mut hmac = Hmac::new(match myType {
       MyType::Type1 => Sha256::new(),
       MyType::Type2 => Sha384::new(),
       MyType::Type3 => Sha512::new(),
       _ => panic!()
     }, my_secret.to_string().as_bytes()
 note: match arm with an incompatible type
       MyType::Type2 => Sha384::new(),
                                         ^~~~~~~~~~~~~
 help: methods from traits can only be called if the trait is implemented and in scope; the following traits define a method `input`, perhaps you need to implement one of them:
 help: candidate #1: `crypto::cryptoutil::FixedBuffer`
 help: candidate #2: `crypto::digest::Digest`
 help: candidate #3: `crypto::mac::Mac`
 help: methods from traits can only be called if the trait is implemented and in scope; the following traits define a method `result`, perhaps you need to implement one of them:
 help: candidate #1: `crypto::digest::Digest`
 help: candidate #2: `crypto::mac::Mac`
```

**Comment by DaGenix** [comment]
I think the problem is that the compiler is being given conflicting information about what the type of the `hmac` variable is.

The definition of Hmac is `Hmac<D>` where `D` is a `Digest`. The problem is that `Digest<D>` isn't really a type - its a type constructor. Given a parameter which implements the `Digest` trait, it will produce an actual type. In this case, depending on the value of `myType`, you can end up with the actual type of `Hmac<Sha256>`, `Hmac<Sha384>`, or `Hmac<Sha512>`.  The `hmac` variable can only have a single type, however. So, I believe that the comiler is complaining that it can't figure out what the type of `hmac` should be since there are 3 possibilities and there is no way to tell what the type of `hmac` needs to be until runtime.

In order for the code you have to work, you would need to pass a trait object into the Hmac constructor. Something like:

```rust
    let hmac = crypto::hmac::Hmac::new(
        Box::new(sha2::Sha256::new()) as Box<Digest>,
        "".to_string().as_bytes());
```

Doing that, the type of `hmac` then becomes `Hmac<Box<Digest>>` regardless of if you use Sha256, Sha384, or Sha512. Unfortunately, the Sha2 varients aren't currently useable as trait objects like this, so, that particular code won't currently work (although I hope to make it work in the future).

As an alternative, you can do something like this:

```rust
extern crate crypto;

use crypto::digest::Digest;
use crypto::sha2;

enum MyType {
    Type1,
    Type2,
    Type3
}

fn do_hmac<D>(digest: D) where D: Digest {
    let hmac = crypto::hmac::Hmac::new(
        digest,
        "".to_string().as_bytes());
    // Do you stuff with hmac here...
}

fn main() {
    let ty = MyType::Type1;

    match ty {
        MyType::Type1 => do_hmac(sha2::Sha256::new()),
        MyType::Type2 => do_hmac(sha2::Sha384::new()),
        MyType::Type3 => do_hmac(sha2::Sha512::new())
    }
}
```

Thats certainly not the only way to solve this problem, of course. The key is making sure that the type of `hmac` is well defined. In this case, its well defined because `do_hmac` is polymorphic over the type of digest function that is passed in. In the body fo the function, the type parameter `D` only has a single type. As a result, the `hmac` variable has a single type as well.

**Comment by GildedHonour** [comment]
Thanks. I wonder, is Rust so much different than, say, Scala, Java or C#? It were Scala (traits) or C# (interfaces), the code would compile well, right?

**Comment by GildedHonour** [comment]
Isn't this ```fn do_hmac<D>(digest: D) where D: Digest {``` the same as ``fn do_hmac<D>(digest: Digest) {```?

**Comment by DaGenix** [comment]
I believe that the problem you are running into is one that you would hit in any statically typed langauge. The problem, I think, is that you can't write out the type for `hmac` and if you can't write it out, the compiler can't either.

Imagine the Java code:

```java
public ? some_func(boolean x) {
    if (x) {
        return 'a';
    } else {
        return 1;
    }
}
```

What should the return type of the function be? Since it could return wither a `char` or an `int`, its not possible to write it out and thus its not valid Java code.

If you tried to convert your problem code into C# / Java / Scala, I believe that it would probably appear to work. Well, it would work, but, it would also probably be doing something fundamentally different. Lets say you have the Java code:

```java
interface Digest { ... }

class Hmac {
    private final Digest d;
    public Hmac(Digest d) {
        this.d = d
    }
}
```

That code will work fine regardless of it you pass it a Sha256 instance or a Sha384 instance. Whats happening in this code, however, is different than whats going on with the Rust code that won't compile, though. In this case, the value `d` is a reference to an object that implements the `Digest` interface. Regardless of if Sha256 or Sha 384 or some other hash is passed in, the size of `d` remains the same - just the size of a reference. As a result, the size of the `Hmac` class is also constant - just the size of whatever other fields it might have, general object overhead, and the size of a reference to `d` on whatever platform you are running. Since we're just passing a generic reference into `Hmac`, however, the code can't be optimized for the type of digest that we pass in. In all cases, any time that `Hmac` wants to call a method on `d`, it need to do a virtual call. So, it looks up the vtable for `d`, find the function it wants to call in that table, and then invokes the function. `Hmac` is a propper type (in Haskell terms). Whether or not you pass in a Sha256 or Sha384 instance into the `Hmac` constuctor you end up with the exact same resulting type - an `Hmac` instance that has to do virtual call on the provided digest.

The Rust code, however, is doing something subtly, but significantly different. When you create an Hmac instance using Rust-Crypto's `Hmac` struct, you actually end up producing a different type for each type of digest that you might pass in. If you pass in a Sha256 instance, you create `Hmac<Sha256>`. If you pass in a Sha384 instance, you create a `Hmac<Sha384>`. `Hmac<Sha256>` and `Hmac<Sha384>` are fully distinct types. Unlike the Java case, where the digest we pass in is just a fixed sized reference, in this case, we are pasing in the actual object. `Hmac` stores the object inline with its other data members. So, the size of `Hmac<Sha256>` and `Hmac<Sha384>` are very likely different (if Sha256 and Sha384 are different). The benefit of this is that we have one fewer allocation and also that we can be more efficient than Java can. `Hmac<Sha256>` knows that its digest is always a Sha256. So, there is no reason to have to do a virtual call. So, instead of doing the vtable dance that Java has to do, `Hmac<Sha256>` can just directly call the methods on Sha256 that it needs. Similarly, `Hmac<Sha384>` can do the same thing with Sha384. What this means, of course, is that while both `Hmac<Sha256>` and `Hmac<Sha384>` have a method called `input()`, the actual implementations of those methods are completely different since they are specialized to the particular digest being used.

In the Rust-Crypto case, Hmac is not a propper type. It is a type constructor. Its not possible to create an instance of Hmac since Hmac needs to know the type of digest that it will use. Instead, we can provide the name of the Digest to use to Hmac to construct an actual type. So, Sha256 + Hmac = Hmac<Sha256>; Sha384 + Hmac = Hmac<Sha384>. Hmac<Sha256> is a propper type and we can construct an instance of it.

The Rust behavior that I describe above, I believe, is technically known as monomorphisation. Basically, whenever we have a type parameter, the compiler will create a specialized version of the function or struct for those type parameters. This is basically how C++ templates work. Its very different than how Generics work in Java, however, since in Java Generics are basically just a compiler hack that allows you do do less type casting but otherwise don't really do anything (I'm less familiar with how Generics work in Scala / C# so I will avoid commenting on them to hopefully avoid embaressing myself).

Anyway, since `Hmac<Sha256>` and `Hmac<Sha384>` are completely different types with different sizes and different methods, it means that its not possible to delcare a variable as just an `Hmac` and then do anything with it - the function won't know what type of Hmac it is and thus won't be able to call any methods on it or allocate stack space for it. The way to handle this in Rust, is to create a generic function that can work on an `Hmac<D>` where D is some type that implements `Digest`. Much as Rust will generate completely different code for `Hmac<Sha256>` than for `Hmac<Sha384>`, when you have a generic function like I described above, it will generate completely different code for that funtion depending on the actual type of D. Since different versions of the function are generated for each type of D, it solves the problems of using a generic `Hmac` type. If you have the code:

```rust
fn do_hmac<D>(digest: D) where D: Digest {
    let hmac = crypto::hmac::Hmac::new(
        digest,
        "".to_string().as_bytes());
    // Do you stuff with hmac here...
}
```

What you are asking Rust to do is to generate a different version of this function when D is Sha256 than when D is Sha384. Since we get different versions of the function, it can generate specialized code for handling an `Hmac<Sha256>` and different code for a `Hmac<Sha384>`. Since we're generating specialized code, it means that we know exactly how big the hmac value is and which methods it has which allows everything to compile.

Since we have many versions of do_hmac, it means that we need to be able to tell which version we actually want to call when we call it. We can tell the compiler this based on the type of the digest object that we pass in. However, lets say that the function that calls do_hmac also wants to be able to accept a digest as a function: In that case, we need to make that function generic as well.

So, this is how Rust and Java differ in this respect. Its also possible to get behavior very similar to Java's in Rust. The key is that we need to use the same mechanism that makes it work in Java - dynamic dispatch. With dynamic dispatch, we can pass a fixed size reference around and we can look up the actual methods to execute on that reference at runtime using the vtable. The way that this is done in rust is by using a trait object. You can create a trait object by doing something like:

```rust
Box::new(sha2::Sha256::new()) as Box<Digest>
```

In this case, we're createing a Sha256 instance and then casting it into a `Digest`. Notice that we're creating the instance inside a `Box` - this is just Rusts term for saying that we're creating it behind a pointer. To compare with Java - in Java, all objects are boxed and there is no way to create an un-boxed object (ie: one that is on the stack and not being a pointer). In Rust, we can create either type of object - more flexibility, but also more complexity.

If we can pass a boxed Digest object to Hmac as the digest, then Rust will create an Hmac instance that uses the Digest behind a pointer and uses dynamic dispatch just like Java would. Behind a pointer using dynamic dispatch, Sha256 looks just like Sha384. So, in that case, the Rust code ends up working just like the Java code would.

When we write code like:

```rust
do_hmac(digest: &Digest)
```

we're declaring that `digest` is a trait object and that it uses dynamic dispatch. However, when we write code like:

```rust
fn do_hmac<D>(digest: D) where D: Digest
```

what we're doing is creating a generic function that Rust will create a specialized version of for any object that implements the `Digest` trait. In my oppinion, this is one place where the Rust syntax can be a little confusing. The key is, if you see a trait being used in a place where a type is expected, that means that you're dealing with a trait object and thus dynamic dispatch. If you see a trait being used to constrain a generic type parameter, you are dealing with monomorphisation and static dispatch.

Anyway, when we use a trait object as the parameter for Hmac, we end up creating the a type like `Hmac<Box<Digest>>`. In this case, any digest as a trait object will work fine - Sha256, Sha384 or some other type.

Unfortunately, its not possible to currently use the Rust-Crypto digest objects in this way. I hope to either update Rust-Crypto so that Digest objects are usable in this manner, or, even better, I think that Rust may be getting an update to make this happen more easily without changes to Rust-Crypto. I'm planning on doing a bit more research to see what the plans for Rust are.

**Comment by GildedHonour** [comment]
Thanks a lot. So Rust is different from Java and C# and in this aspect?

Regarding your example.

```
public ? some_func(boolean x) {
    if (x) {
        return 'a';
    } else {
        return 1;
    }
}
```
What if Char and Integer implemented one common interface?

interface Interface1 {
  //....
}
class Char implements Interface1 {
 //..
}

class Integer implements Interface1 {
 //..
}

Then:

```
public Interface1 some_func(boolean x) {
    if (x) {
        return 'a';
    } else {
        return 1;
    }
}
```
It should compile very well.

**Comment by ebfe** [comment]
To do this you would need a Box<Trait>. Maybe this is what you want:

    extern crate crypto;
    
    use crypto::sha2::{Sha256, Sha384, Sha512};
    use crypto::hmac::Hmac;
    use crypto::digest::Digest;
    use crypto::mac::{Mac, MacResult};
    
    
    enum MyType {
        Type1,
        Type2,
        Type3
    }
    
    fn do_hmac(typ : MyType, input : &[u8]) -> MacResult {
        let secret = "secret";
    
        let mut mac = match typ {
            MyType::Type1 => Box::new(Hmac::new(Sha256::new(), secret.as_bytes())) as Box<Mac>,
            MyType::Type2 => Box::new(Hmac::new(Sha384::new(), secret.as_bytes())) as Box<Mac>,
            MyType::Type3 => Box::new(Hmac::new(Sha512::new(), secret.as_bytes())) as Box<Mac>,
        };
    
        mac.input(input);
        mac.result()
    }
    
    pub fn main() {
        println!("{:?}", do_hmac(MyType::Type1, "blablabla".as_bytes()).code())
    }

**Comment by GildedHonour** [comment]
@ebre, I want to avoid using Box for now. I tried the solution DaGenix suggested and it didn't pan out for me, may be because I missed something. Could you show me how to do it using `fn do_hmac<D: Digest>(digest: D) ` approach?

**Comment by GildedHonour** [comment]
Here's a simplified version having the same error as I had before:

```
fn some_main_fun(my_type: MyType, some_str: &[u8])
  let mut hmac = match my_type {
    MyType::MyType1 => create_hmac(Sha256::new(), some_str),
    MyType::MyType2 => create_hmac(Sha384::new(), some_str),
    MyType::MyType3 => create_hmac(Sha512::new(), some_str),
    _ => panic!()
  };

  //some calculations HERE, NOT in create_hmac function...
  hmac.input("fdsfdsfdsfd".to_string().as_bytes());
}

fn create_hmac<D: Digest>(digest: D, some_str: &str) -> Hmac<D> {
  Hmac::new(digest, some_str.to_string().as_bytes()) 
  // nothing ....
}
```

What am I missing?

**Comment by ebfe** [comment]
On Sun, Feb 08, 2015 at 05:33:35AM -0800, Alex Maslakov wrote:
> @ebre, I want to avoid using Box for now. 

I can't think of a solution that doesn't involve Box<SomeTrait>.

**Comment by DaGenix** [comment]
@GildedHonour `char` and `int` are unboxed values in Java. Their corresponding classes, `Character` and `Integer` are both boxed types (like all Objects in Java). If we assumed that there was some new interface, `Interface1`, implemented by both `Character` and `Integer`, we would be able to return an instance of either from the same function. However, what the code would look like would be:

```java
public Interface1 some_func(boolean x) {
    if (x) {
        return new Character('a');
    } else {
        return new Integer(1);
    }
}
```

 In other words, we would have to box the value before returning it (side note: due to Java use of auto-boxing which will often times hide when a value is boxed vs. non-boxed, this may not have been a great example for me to pick).

The equivalent Rust code to the above would be:

```rust
fn some_func(x: bool) -> Box<Interface1> {
    if x {
        return Box::new('a') as Box<Interface1>;
    } else {
        return Box::new(1) as Box<Interface1>;
    }
}
```

Regarding your specific problem, I believe that your only options are to box the value returned by `create_hmac()` or to make the function that uses the result of `create_hmac()` also generic over the digest or mac type. If there are other solutions to this problem, I don't know them.

**Comment by GildedHonour** [comment]
Makes sense.
