### ISSUE TITLE
Allow changing block size of BlockEncryptor & BlockDecryptor

### ISSUE THREAD

**Issue by danielrs** [DaGenix/rust-crypto#394]
I'm using `rust-crypto` in my library, however, I ran into an issue. I need to use Blowfish (ECB mode) with a block size of 4 bytes, but the rust-crypto uses blocks of 1 byte internally, without providing any means to override this.

See related #393

**Comment by adam-frisby** [comment]
Blowfish is defined as having a 64-bit (8 byte) block. You would need to change the entire algorithm to support a 4-byte block at which point it is no longer blowfish.

You could take concepts from Blowfish to create a custom 4-byte block cipher but you would invariably be creating a weaker algorithm. Newer algorithms like AES use larger block sizes (16 bytes) and are more secure because of it.

**Comment by danielrs** [comment]
@pix64 My mistake, was thinking about something else when reading the source code.
