### ISSUE TITLE
Non-deterministic result from the example in some cases

### ISSUE THREAD

**Issue by behos** [DaGenix/rust-crypto#396]
Hi,

I'm getting some weird behaviour when using the example for encryption.

I took the implementation from the example:

```
fn encrypt_bytes(
    data: &[u8], key: &[u8], iv: &[u8]
) -> Result<Vec<u8>, Box<Error>> {

    println!("{:?} {:?} {:?}", data, key, iv);
    let mut encryptor = aes::cbc_encryptor(
        aes::KeySize::KeySize256,
        key,
        iv,
        blockmodes::PkcsPadding
    );

    let mut final_result = Vec::<u8>::new();
    let mut read_buffer = RefReadBuffer::new(data);
    let mut buffer = [0; 4096];
    let mut write_buffer = RefWriteBuffer::new(&mut buffer);

    loop {
        let error: Result<BufferResult, Box<Error>> = Err(
            From::from("Failed encryption")
        );

        let result= try!(
            encryptor.encrypt(&mut read_buffer, &mut write_buffer, true)
                .or(error)
        );

        final_result.extend(
            write_buffer.take_read_buffer()
                .take_remaining().iter().map(|&i| i)
        );
        match result {
            BufferResult::BufferUnderflow => break,
            BufferResult::BufferOverflow => {}
        }
    }
    println!("{:?}", final_result);
    Ok(final_result)
}
```

The only difference is the rewriting of the error type.

Running this multiple times gives different results even though the inputs seem to be the same.

In: [112, 97, 115, 115, 119, 111, 114, 100] [115, 111, 109, 101, 32, 110, 105, 99, 101, 32, 107, 101, 121] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Out: [36, 5, 135, 130, 138, 234, 241, 198, 90, 139, 208, 105, 238, 10, 151, 4]

In: [112, 97, 115, 115, 119, 111, 114, 100] [115, 111, 109, 101, 32, 110, 105, 99, 101, 32, 107, 101, 121] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Out: [255, 250, 115, 56, 233, 253, 108, 254, 250, 186, 94, 86, 5, 130, 205, 247]

In: [112, 97, 115, 115, 119, 111, 114, 100] [115, 111, 109, 101, 32, 110, 105, 99, 101, 32, 107, 101, 121] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Out: [0, 75, 143, 128, 108, 132, 30, 212, 208, 236, 237, 149, 146, 245, 239, 218]

I'm pretty sure I must be missing something here, but I couldn't find something obvious.

Any idea what I'm doing wrong here?

**Comment by behos** [comment]
Closing this. Looking into this a bit more seems to be an issue elsewhere

**Comment by niluxv** [comment]
The problem is, you are providing a 13 byte key while choosing a keysize of 256 bits (32 bytes). This causes a buffer underflow in the C-code that handles aes-ni. The first 19 bytes in memory after your key are also used as key for encryption/decryption. This makes the function non-deterministic.
See also [this issue](https://github.com/DaGenix/rust-crypto/issues/404).
The rust binding to the aes-ni implementation should assert that the key length equals the key size. See [this commit](https://github.com/niluxv/rust-crypto/commit/def5fd6e74c0d8208ab84e0138b7c01ed53fb0ea) in [Rust-crypto-maintained](https://github.com/niluxv/rust-crypto).
