### ISSUE TITLE
AESNI problems with cloned keys

### ISSUE THREAD

**Issue by astonbitecode** [DaGenix/rust-crypto#404]
I have a case where rust-crypto seems not to work correctly when using AESNI.

The code that reproduces the issue can be found [here](https://gist.github.com/astonbitecode/100b45c84c24d9ccf2172dbdaf5aad54), but a brief description is that rust-crypto does not encrypt / decrypt correctly when using a cloned key.

The encryption / decryption should not be influenced from the fact that the key that is used for the operation is cloned... or should it? I would expect that since the actual data of a key is the same, the operation should succeed regardless if the key is cloned or not.

# Reproducing code

```rust

#[test]
fn failure() {

	// Initialize the data, key and iv
	let data = vec![0x10u8, 0x11u8, 0x12u8, 0x10u8, 0x11u8, 0x12u8,0x10u8, 0x11u8, 0x12u8,0x10u8, 0x11u8, 0x12u8,0x10u8, 0x11u8, 0x12u8, 0x10u8];
	let key = vec![0x10u8, 0x41u8, 0x04u8, 0x10u8, 0x41u8, 0x04u8, 0x10u8, 0x41u8, 0x04u8, 0x10u8, 0x41u8, 0x04u8, 0x10u8, 0x41u8, 0x04u8, 0x10u8];
	let iv = vec![0x11u8, 0x43u8, 0x03u8, 0x10u8, 0x43u8, 0x03u8, 0x10u8, 0x43u8, 0x03u8, 0x10u8, 0x43u8, 0x03u8, 0x10u8, 0x43u8, 0x03u8, 0x10u8];
	println!("Plain: {:?}", data);
	println!("iv: {:?}", iv);

	// Encrypt
	println!("Encrypting with key {:?}", key);
	let encrypted: Vec<u8> = super::do_encryption(&data, &key, &iv).unwrap();
	println!("Encrypted {:?}", encrypted);

	// Clone the key
	let cloned_key: Vec<u8> = key.iter().cloned().collect();

	// Assert that the cloned key is the same with the original one
	assert!(cloned_key == key);

	// Decrypt using the cloned key
	println!("Decrypting with key {:?}", cloned_key);
	let decrypted = super::do_decryption(&encrypted, &cloned_key, &iv).unwrap();
	println!("Decrypted {:?}", decrypted);

	// Assertion fails!
	assert!(data == decrypted);
}
```

**Comment by niluxv** [comment]
Actually the problem is not the cloning process. The cloned key is identical to the original key (like you asserted).
The problem is, you are providing a 16 byte key while choosing a keysize of 256 bits (32 bytes). This causes a buffer underflow in the C-code that handles aes-ni. Because the memory address of the cloned key differs from the original one, the bytes after the first 16 bytes differ, resulting in a different key and thus a different encryption/decryption.
The rust binding to the aes-ni implementation should assert that the key length equals the key size.
To solve this issue, you just have to change the keysize (in do_encrypt and do_decrypt functions) to `aes::KeySize::KeySize128` (instead of `aes::KeySize::KeySize256`).

**Comment by astonbitecode** [comment]
You are totally right! I missed that.

Thank you
